# Generated by Django 4.0.4 on 2022-07-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memberTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=5)),
                ('member_id', models.CharField(max_length=20)),
                ('member_password', models.CharField(max_length=20)),
                ('member_name', models.CharField(max_length=10)),
                ('member_nickname', models.CharField(max_length=10)),
                ('member_email', models.CharField(max_length=35)),
                ('member_gender', models.CharField(max_length=1)),
                ('member_dob', models.DateField()),
                ('member_join_date', models.DateTimeField(auto_now=True)),
                ('member_pic', models.TextField()),
            ],
        ),
    ]
