# Generated by Django 4.0.4 on 2022-07-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membertest',
            name='id',
        ),
        migrations.AlterField(
            model_name='membertest',
            name='member_code',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
