# Generated by Django 4.0.4 on 2022-07-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_membertest_id_alter_membertest_member_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertest',
            name='member_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
